export let circles = [
    {
        name: 'oxfordshire',
        title: 'Oxfordshire',
        teams: [],
        coach: '',
    },
    {
        name: 'northeast',
        title: 'North East',
        teams: [],
        coach: '',
    }
];

export let teams = [
    {
        name: 'oxford',
        title: 'Oxford',
        circle: 'oxfordshire',
        colleagues: [], 
        capacity: 708,
        utilisation: 65
    }
];

export let colleagues = [
    {
        id: 0001
        name: 'Adam Mitchell',
        photo: './rota/colleagues/adam-mitchell.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 140,
        contactHours: 80,
        mileage: 0,
        annualLeave: false,
        annualLeaveAllowance: 12,
        absence: false,
        mobile: '07778987654',
        email: 'adam.mitchell@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shifts: [],
        visits: [],
        contractStartDate: '2020-11-02',
        probation: true,
    },
    {
        id: 0002,
        name: 'Amelia Pond',
        photo: './rota/colleagues/amelia-pond.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 48,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 6,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0003,
        name: 'Bill Potts',
        photo: './rota/colleagues/bill-potts.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 120,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 24,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0004,
        name: 'Clara Oswald',
        photo: './rota/colleagues/clara-oswald.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 60,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 14,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0005,
        name: 'Jack Harkness',
        photo: './rota/colleagues/jack-harkness.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 60,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 4,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0006,
        name: 'Rory Williams',
        photo: './rota/colleagues/rory-williams.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 60,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 8,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0007,
        name: 'Rose Tyler',
        photo: './rota/colleagues/rose-tyler.png',
        role: 'Rota Champion',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 140,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 24,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0008,
        name: 'Ryan Sinclair',
        photo: './rota/colleagues/ryan-sinclair.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: 60,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: 12,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0009,
        name: 'Sarah J Smith',
        photo: './rota/colleagues/sarah-j-smith.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: ,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: ,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    },
    {
        id: 0010,
        name: 'Yasmin Khan',
        photo: './rota/colleagues/yasmin-khan.png',
        role: 'Wellbeing Support Worker',
        team: 'Oxford',
        linkWorker: null,
        contractedHours: ,
        contactHours: ,
        availability: ,
        mileage: ,
        annualLeave: ,
        absence: ,
        mobile: ,
        email: '@belleviecare.co.uk',
        slack: 'https://bellevie-for-all.slack.com/archives/D01DYEVSJN5',
        shift: ,
        visits: [],
        contractStartDate: ,
        probation: true,
    }
    
];

export let week = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

export let shifts = [
    {
        day: ,
        startTime: ,
        visits: ,
        colleagues: ,
        totalTravelTime: ,
        totalMileage:
        }
];

export let activities = [
    {
        type: ,
        startTime: ,
        endTime: ,
        date: ,
        person: ,
        colleagues: ,
        shift:
    }
];

export let people = [
    {
        name: ,
        address: ,
        linkWorker:,
        visits:
    }
];