/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:b3f4bb31-7bbf-475f-82ca-90a14afe1b4f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_SWQxleIPz",
    "aws_user_pools_web_client_id": "4poq0k17ibu2ltrsra30nu4jis",
    "oauth": {
        "domain": "5d7cl01ksw3s-prod.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://colleagues.belleviecare.co.uk/",
        "redirectSignOut": "https://colleagues.belleviecare.co.uk/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
